name: Update Energy Data

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install yfinance

      - name: Run script
        run: python scripts/fetch_data.py

      - name: Commit data
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add data/*.json
          git commit -m "update data" || echo "no changes"
          git push